# Contains a list of valid topic values that can be
# used in annotations.

[virtue]
values = [
    "faith",
    "hope",
    "charity",

    "humility",
    "obedience",
    "fortitude",
    "patience",
    "mercy",
    "chastity",
    "joy",
    "simplicity",
    "poverty",
]

[theme]
values = [
    "order_of_friars_minor",
    "order_of_saint_clare",
    "third_order",
    "conversion",
    "rule",
    "preaching",
    "stigmata",
    "miracle",
    "vision",
    "mission",
    "cross",
    "death",
    "baptism",
    "eucharist",
    "reconciliation",
    "marriage",
    "holy_order",
    "anointment",
    "fasting",
    "prayer",
    "canticle_of_the_sun"
]

[person]
values = [
    "st_francis_of_assisi",
    "st_clare_of_assisi",

    "pica_de_bourlemont",
    "pietro_di_bernardone",
    "bishop_guido_of_assisi",

    "pope_innocent_iii",
    "pope_honorius_iii",
    "pope_gregory_ix",

    "fr_bernard_of_quintavalle",
    "fr_peter_catanii",
    "fr_elias_of_cortona",
    "fr_giles_of_assisi",
    "fr_leo",
    "fr_rufino_of_assisi",
    "fr_angelo_tancredi",
    "fr_masseo_of_marignano",
    "fr_juniper",
    "fr_illuminato_of_rieti",
    "brother_pacifico",

    "st_dominic",
    "sultan_al_kamil",

    "lady_jacopa_dei_settesoli",

    "thomas_of_celano",
    "st_bonaventure"
]

[place]
values = [
    "assisi",
    "portiuncula",
    "basilica_of_st_mary_of_the_angels",
    "san_damiano",
    "rivotorto",
    "eremo_delle_carceri",

    "greccio",
    "la_verna",

    "bevagna",
    "gubbio",

    "spoleto",
    "foligno",
    "perugia",
    "bologna",
    "siena",
    "fonte_colombo",
    "cortona",
    "nocera_umbra",

    "rome",

    "damietta",
    "egypt",
    "holy_land"
]

[event]
values = [
    "conversion_of_francis",
    "vision_of_san_damiano_crucifix",
    "renunciation_of_possessions",
    "repair_of_san_damiano_and_churches",
    "encounter_with_leper",

    "calling_of_the_first_brothers",
    "approval_of_the_rule_1209",

    "preaching_to_the_birds",
    "wolf_of_gubbio",
    "journey_to_the_sultan_and_east",

    "chapter_of_mats",
    "canticle_of_the_sun",

    "imprinting_of_the_stigmata",

    "death_of_francis_passing_of_francis",
    "canonization_1228",
    "translation_1230"
]
